# Generated by Django 2.2.6 on 2019-10-21 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('ImageId', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('Like', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=20)),
                ('ProductId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('ProductId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=50)),
                ('ProductCategory', models.CharField(max_length=20)),
                ('ProductPrice', models.CharField(max_length=20)),
                ('ProductDate', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
                ('ProductType', models.CharField(max_length=20)),
                ('UserId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProImageModel',
            fields=[
                ('ProductId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ImageId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SaleModel',
            fields=[
                ('SaleId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SaleDate', models.DateTimeField(blank=True, default=datetime.date.today, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserImageModel',
            fields=[
                ('UserId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('ImageId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('UserId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('UserNameSet', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('KakaoId', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
