# Generated by Django 2.2.6 on 2019-10-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('UserId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Password', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('KakaoId', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=50)),
                ('Test777', models.CharField(max_length=50)),
            ],
        ),
    ]
